//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RHEntities : DbContext
    {
        public RHEntities()
            : base("name=RHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Notificacion_Departamento> Notificacion_Departamento { get; set; }
        public virtual DbSet<SYA_Aplicaciones> SYA_Aplicaciones { get; set; }
        public virtual DbSet<SYA_Departamentos> SYA_Departamentos { get; set; }
        public virtual DbSet<SYA_Modulos> SYA_Modulos { get; set; }
        public virtual DbSet<SYA_Usuarios_Modulos> SYA_Usuarios_Modulos { get; set; }
        public virtual DbSet<SYA_Recientes> SYA_Recientes { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<PeriodoVacaciones> PeriodoVacaciones { get; set; }
        public virtual DbSet<Cliente_Departamento> Cliente_Departamento { get; set; }
        public virtual DbSet<Plantilla> Plantilla { get; set; }
        public virtual DbSet<Notificacion_Comentarios> Notificacion_Comentarios { get; set; }
        public virtual DbSet<Notificaciones_Favoritas> Notificaciones_Favoritas { get; set; }
        public virtual DbSet<NOM_Cliente_Conceptos> NOM_Cliente_Conceptos { get; set; }
        public virtual DbSet<NOM_Ejercicio_Fiscal> NOM_Ejercicio_Fiscal { get; set; }
        public virtual DbSet<DocumentosEmpleados> DocumentosEmpleados { get; set; }
        public virtual DbSet<NOM_Empleado_Conceptos> NOM_Empleado_Conceptos { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<HistorialPagos> HistorialPagos { get; set; }
        public virtual DbSet<Notificacion_Status> Notificacion_Status { get; set; }
        public virtual DbSet<C_Metodos_Pago> C_Metodos_Pago { get; set; }
        public virtual DbSet<C_DiasFestivos> C_DiasFestivos { get; set; }
        public virtual DbSet<C_DocumentosTipo> C_DocumentosTipo { get; set; }
        public virtual DbSet<C_Esquema> C_Esquema { get; set; }
        public virtual DbSet<C_Estado> C_Estado { get; set; }
        public virtual DbSet<C_FactoresIntegracion> C_FactoresIntegracion { get; set; }
        public virtual DbSet<C_NOM_Conceptos_SAT> C_NOM_Conceptos_SAT { get; set; }
        public virtual DbSet<C_NOM_Tabla_IMSS> C_NOM_Tabla_IMSS { get; set; }
        public virtual DbSet<C_NOM_Tabla_ISR> C_NOM_Tabla_ISR { get; set; }
        public virtual DbSet<C_NOM_Tabla_Subsidio> C_NOM_Tabla_Subsidio { get; set; }
        public virtual DbSet<C_NotificacionTipo> C_NotificacionTipo { get; set; }
        public virtual DbSet<C_PeriodicidadPago_SAT> C_PeriodicidadPago_SAT { get; set; }
        public virtual DbSet<C_TipoContrato_SAT> C_TipoContrato_SAT { get; set; }
        public virtual DbSet<C_TipoIncapacidad_SAT> C_TipoIncapacidad_SAT { get; set; }
        public virtual DbSet<C_TipoJornada_SAT> C_TipoJornada_SAT { get; set; }
        public virtual DbSet<C_TipoNomina_SAT> C_TipoNomina_SAT { get; set; }
        public virtual DbSet<C_TipoRegimen_SAT> C_TipoRegimen_SAT { get; set; }
        public virtual DbSet<C_TiposInasistencia> C_TiposInasistencia { get; set; }
        public virtual DbSet<SYA_GlobalConfig> SYA_GlobalConfig { get; set; }
        public virtual DbSet<SYA_Perfiles> SYA_Perfiles { get; set; }
        public virtual DbSet<SYA_Usuarios> SYA_Usuarios { get; set; }
        public virtual DbSet<C_Banco_SAT> C_Banco_SAT { get; set; }
        public virtual DbSet<C_TipoOtroPago_SAT> C_TipoOtroPago_SAT { get; set; }
        public virtual DbSet<UserConfig> UserConfig { get; set; }
        public virtual DbSet<Kardex> Kardex { get; set; }
        public virtual DbSet<C_RegimenFiscal_SAT> C_RegimenFiscal_SAT { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<ZonaSalario> ZonaSalario { get; set; }
        public virtual DbSet<ParametrosConfig> ParametrosConfig { get; set; }
        public virtual DbSet<NOM_Facturacion> NOM_Facturacion { get; set; }
        public virtual DbSet<NOM_FacturacionSindicato> NOM_FacturacionSindicato { get; set; }
        public virtual DbSet<C_NOM_Conceptos> C_NOM_Conceptos { get; set; }
        public virtual DbSet<NOM_Empleado_Complemento> NOM_Empleado_Complemento { get; set; }
        public virtual DbSet<CumpleIMSS> CumpleIMSS { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<NOM_FacturacionC_Finiquito> NOM_FacturacionC_Finiquito { get; set; }
        public virtual DbSet<NOM_FacturacionComplemento> NOM_FacturacionComplemento { get; set; }
        public virtual DbSet<NOM_FacturacionF_Finiquito> NOM_FacturacionF_Finiquito { get; set; }
        public virtual DbSet<NOM_Empleado_Sindicato> NOM_Empleado_Sindicato { get; set; }
        public virtual DbSet<NOM_Nomina_Ajuste> NOM_Nomina_Ajuste { get; set; }
        public virtual DbSet<ClavesContables> ClavesContables { get; set; }
        public virtual DbSet<NOM_Finiquito_Descuento_Adicional> NOM_Finiquito_Descuento_Adicional { get; set; }
        public virtual DbSet<C_NOM_Conceptos_C> C_NOM_Conceptos_C { get; set; }
        public virtual DbSet<NOM_Nomina_Detalle_C> NOM_Nomina_Detalle_C { get; set; }
        public virtual DbSet<NOM_Finiquito_Detalle> NOM_Finiquito_Detalle { get; set; }
        public virtual DbSet<Sucursal_Empresa> Sucursal_Empresa { get; set; }
        public virtual DbSet<NOM_CFDI_Timbrado> NOM_CFDI_Timbrado { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Inasistencias> Inasistencias { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
        public virtual DbSet<NOM_Cuotas_IMSS> NOM_Cuotas_IMSS { get; set; }
        public virtual DbSet<NOM_Empleado_Asimilado> NOM_Empleado_Asimilado { get; set; }
        public virtual DbSet<NOM_Incapacidad> NOM_Incapacidad { get; set; }
        public virtual DbSet<NOM_Aguinaldo> NOM_Aguinaldo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Empleado_Fonacot> Empleado_Fonacot { get; set; }
        public virtual DbSet<NOM_PeriodosPago> NOM_PeriodosPago { get; set; }
        public virtual DbSet<DatosBancarios> DatosBancarios { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empleado_Contrato> Empleado_Contrato { get; set; }
        public virtual DbSet<NOM_Nomina_Detalle> NOM_Nomina_Detalle { get; set; }
        public virtual DbSet<HorasExtrasEmpleado> HorasExtrasEmpleado { get; set; }
        public virtual DbSet<Empleado_Infonavit> Empleado_Infonavit { get; set; }
        public virtual DbSet<NOM_Empleado_PeriodoPago> NOM_Empleado_PeriodoPago { get; set; }
        public virtual DbSet<NOM_Nomina> NOM_Nomina { get; set; }
        public virtual DbSet<Incapacidades> Incapacidades { get; set; }
        public virtual DbSet<NOM_Finiquito> NOM_Finiquito { get; set; }
        public virtual DbSet<NOM_Finiquito_Complemento> NOM_Finiquito_Complemento { get; set; }
        public virtual DbSet<NOM_Nomina_PrimaVacacional> NOM_Nomina_PrimaVacacional { get; set; }
        public virtual DbSet<NOM_Nomina_Incidencias> NOM_Nomina_Incidencias { get; set; }
    }
}
