//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClavesContables
    {
        public int IdClaveContable { get; set; }
        public int IdConcepto { get; set; }
        public int IdEmpresa { get; set; }
        public string Acredora { get; set; }
        public string Deudora { get; set; }
    }
}
