//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumpleIMSS
    {
        public int IdCumpleIMSS { get; set; }
        public int IdContrato { get; set; }
        public System.DateTime FechaIMSS { get; set; }
        public int Anio { get; set; }
        public decimal FactorIntegracion { get; set; }
        public decimal SDIViejo { get; set; }
        public decimal SDINuevo { get; set; }
        public int IdEmpresaEmpleado { get; set; }
        public int Usuario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
