//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosBancarios
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public int IdBanco { get; set; }
        public Nullable<int> NoSigaF { get; set; }
        public Nullable<int> NoSigaC { get; set; }
        public string CuentaBancaria { get; set; }
        public string NumeroTarjeta { get; set; }
        public string Clabe { get; set; }
        public string NombreBeneficiario { get; set; }
        public string CURPBeneficiario { get; set; }
        public string RFCBeneficiario { get; set; }
        public string ParentezcoBeneficiario { get; set; }
        public string DomicilioBeneficiario { get; set; }
        public bool Status { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int IdUsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> IdUsuarioMod { get; set; }
    }
}
