//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosEmpleados
    {
        public int IdDocumento { get; set; }
        public int IdEmpleado { get; set; }
        public int IdTipoDocumento { get; set; }
        public string NombreDocumento { get; set; }
        public bool Status { get; set; }
    }
}
