//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Nomina
    {
        public int Id { get; set; }
        public int IdEmpleado { get; set; }
        public int TipoNomina { get; set; }
        public string FormaPago { get; set; }
        public decimal SD { get; set; }
        public decimal SDI { get; set; }
        public decimal SalarioReal { get; set; }
        public string NoSiga1 { get; set; }
        public string NoSiga2 { get; set; }
        public string CuentaBancaria { get; set; }
        public string Clabe { get; set; }
        public string NumeroTarjeta { get; set; }
        public string CuentaBancaria2 { get; set; }
        public string NumeroTarjeta2 { get; set; }
        public int IdBanco { get; set; }
        public int TipoSemana { get; set; }
        public int TipoSalario { get; set; }
    }
}
