//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado_Fonacot
    {
        public int Id { get; set; }
        public int IdEmpleadoContrato { get; set; }
        public string NumCredito { get; set; }
        public decimal MontoInicial { get; set; }
        public int Plazos { get; set; }
        public decimal Retencion { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaInicioDescuento { get; set; }
        public Nullable<System.DateTime> FechaSuspension { get; set; }
        public bool Status { get; set; }
        public System.DateTime FechaReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    }
}
