//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactoresIntegracion
    {
        public int IdFactor { get; set; }
        public int Antiguedad { get; set; }
        public int DiasAguinaldo { get; set; }
        public int DiasVacaciones { get; set; }
        public decimal PrimaVacacional { get; set; }
        public decimal Factor { get; set; }
    }
}
