//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPagos
    {
        public int IdPagos { get; set; }
        public int IdPrestamo { get; set; }
        public int IdNomina { get; set; }
        public decimal CantidadDescuento { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int TipoPrestamo { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public Nullable<decimal> DiasDescontados { get; set; }
    }
}
