//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasExtrasEmpleado
    {
        public int IdHoras { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Horas { get; set; }
        public bool Simples { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> UsuarioMod { get; set; }
    }
}
