//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Nomina_Ajuste
    {
        public int IdAjuste { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpleado { get; set; }
        public int IdConcepto { get; set; }
        public decimal Total { get; set; }
        public decimal GravadoIsr { get; set; }
        public decimal ExentoIsr { get; set; }
        public decimal IntegraImss { get; set; }
        public decimal ImpuestoSobreNomina { get; set; }
        public System.DateTime FechaReg { get; set; }
    }
}
