//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Ejercicio_Fiscal
    {
        public int IdEjercicio { get; set; }
        public string Anio { get; set; }
        public bool Cerrado { get; set; }
        public int Dias { get; set; }
    }
}
