//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_FacturacionC_Finiquito
    {
        public int IdFacturaC_Finiquito { get; set; }
        public int IdFiniquito { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpresa_C { get; set; }
        public decimal C_Percepciones { get; set; }
        public decimal C_Porcentaje_Servicio { get; set; }
        public decimal C_Total_Servicio { get; set; }
        public decimal C_Cuotas_IMSS_Infonavit { get; set; }
        public decimal C_Impuesto_Nomina { get; set; }
        public decimal C_Relativos { get; set; }
        public decimal C_Descuentos { get; set; }
        public decimal C_Otros { get; set; }
        public decimal C_Subtotal { get; set; }
        public decimal C_Total_IVA { get; set; }
        public decimal C_Total_Complemento { get; set; }
    }
}
