//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Finiquito_Detalle
    {
        public int Id { get; set; }
        public int IdFiniquito { get; set; }
        public int IdConcepto { get; set; }
        public decimal Total { get; set; }
        public decimal GravadoISR { get; set; }
        public decimal ExentoISR { get; set; }
        public decimal IntegraIMSS { get; set; }
        public Nullable<int> IdPrestamo { get; set; }
        public decimal ImpuestoSobreNomina { get; set; }
        public bool Liq { get; set; }
    }
}
