//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Facturacion
    {
        public int IdFactura { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpresaFi_As { get; set; }
        public int IdEmpresaCo_Asim { get; set; }
        public decimal IVA { get; set; }
        public decimal F_Cuota_IMSS_Infonavit { get; set; }
        public decimal F_Impuesto_Nomina { get; set; }
        public decimal F_Amortizacion_Infonavit { get; set; }
        public decimal F_Fonacot { get; set; }
        public decimal F_Pension_Alimenticia { get; set; }
        public decimal F_Relativo { get; set; }
        public decimal F_Total_Nomina { get; set; }
        public decimal F_Total_Fiscal { get; set; }
    }
}
