//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Tabla_ISR
    {
        public int IdISR { get; set; }
        public decimal Limite_Inferior { get; set; }
        public decimal Limite_Superior { get; set; }
        public decimal Cuota_Fija { get; set; }
        public decimal Porcentaje { get; set; }
        public int TipoTarifa { get; set; }
    }
}
