//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Aguinaldo
    {
        public int IdAguinaldo { get; set; }
        public int IdEjercicio { get; set; }
        public int IdPeriodo { get; set; }
        public int IdContrato { get; set; }
        public int IdEmpleado { get; set; }
        public int IdNomina { get; set; }
        public decimal SD { get; set; }
        public decimal SDI { get; set; }
        public decimal SalarioMinimo { get; set; }
        public int DiasAguinaldo { get; set; }
        public int DiasEjercicioFiscal { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaPrimerDia { get; set; }
        public Nullable<System.DateTime> FechaUltimoDia { get; set; }
        public int TotalFaltas { get; set; }
        public int Incapacidades { get; set; }
        public int FaltasInjustificadas { get; set; }
        public int PermisoSinGose { get; set; }
        public Nullable<int> FaltasPersonalizadas { get; set; }
        public int DiasTrabajados { get; set; }
        public decimal SueldoMensual { get; set; }
        public decimal Proporcion { get; set; }
        public decimal TopeExcento { get; set; }
        public decimal Aguinaldo { get; set; }
        public decimal Exento { get; set; }
        public decimal Gravado { get; set; }
        public decimal ISR { get; set; }
        public decimal Neto { get; set; }
        public decimal Complemento { get; set; }
        public decimal Total { get; set; }
        public decimal ISN3 { get; set; }
        public decimal Factor { get; set; }
        public System.DateTime FechaReg { get; set; }
        public bool CalcularPensionAlimenticia { get; set; }
        public decimal PensionAlimenticia { get; set; }
        public decimal DiasAguinaldoComp { get; set; }
        public decimal SDR { get; set; }
        public Nullable<System.DateTime> FechaPrimerDiaC { get; set; }
        public decimal ProporcionC { get; set; }
        public int DiasTrabajadosC { get; set; }
    }
}
