//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_FacturacionSindicato
    {
        public int IdFacturaS { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpresaS { get; set; }
        public decimal S_Percepcion_Sindicato { get; set; }
        public decimal S_Porcentaje_Comision { get; set; }
        public decimal S_Total_Comision { get; set; }
        public decimal S_Percepcion_Fiscal { get; set; }
        public decimal S_IVA_Percepcion_Fiscal { get; set; }
        public decimal S_Dif_Montvde { get; set; }
        public decimal S_Cuota_Legado { get; set; }
        public decimal S_Costo_IMSS { get; set; }
        public decimal S_IVA_Costo_IMSS { get; set; }
        public decimal S_Total_Porcentaje_Nomina { get; set; }
        public decimal S_IVA_Porcentaje_Nomina { get; set; }
        public decimal S_Total_Sindicato { get; set; }
    }
}
