//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_PeriodosPago
    {
        public int IdPeriodoPago { get; set; }
        public int IdEjercicio { get; set; }
        public int Bimestre { get; set; }
        public string Descripcion { get; set; }
        public int IdTipoNomina { get; set; }
        public int DiasPeriodo { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public bool Especial { get; set; }
        public bool Ultimo { get; set; }
        public int IdCliente { get; set; }
        public int IdSucursal { get; set; }
        public bool Procesando { get; set; }
        public bool Procesado { get; set; }
        public bool Error_Procesado { get; set; }
        public bool Autorizado { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public int CfdiGenerado { get; set; }
        public Nullable<int> UsuarioAutorizo { get; set; }
        public int IdTipoNominaSat { get; set; }
        public bool SoloComplemento { get; set; }
        public bool Sindicato { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    }
}
