//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Nomina_Incidencias
    {
        public int Id { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> FI { get; set; }
        public string FI_Fecha { get; set; }
        public Nullable<int> FJ { get; set; }
        public string FJ_Fecha { get; set; }
        public Nullable<int> Au { get; set; }
        public string Au_Fecha { get; set; }
        public Nullable<int> IE { get; set; }
        public string IE_Fecha { get; set; }
        public Nullable<int> IM { get; set; }
        public string IM_Fecha { get; set; }
        public Nullable<int> IR { get; set; }
        public string IR_Fecha { get; set; }
        public Nullable<int> Vacaciones { get; set; }
        public string Vacaciones_Fecha { get; set; }
    }
}
