//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Finiquito_Complemento
    {
        public int Id { get; set; }
        public int IdFiniquito { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaBaja { get; set; }
        public System.DateTime FechaInicioAguinaldo { get; set; }
        public System.DateTime FechaInicioVacacion { get; set; }
        public System.DateTime FechaAntiguedadReal { get; set; }
        public int Años_Antiguedad { get; set; }
        public int DiasLaborados { get; set; }
        public int DiasVacacionesParaCalculo { get; set; }
        public int DiasAguinaldoParaCalculo { get; set; }
        public int DiasDocePorA { get; set; }
        public int AguinaldoCorrespondiente { get; set; }
        public int VacacionesCorrespondientes { get; set; }
        public int PrimaVacacional { get; set; }
        public decimal SDReal { get; set; }
        public int DiasEjercicioFiscal { get; set; }
        public decimal L_3Meses_SueldoParaCalculo { get; set; }
        public int SueldoPendiente { get; set; }
        public int VacacionesPendientes { get; set; }
        public int PrimaVacacionPendiente { get; set; }
        public decimal ProporcionalAguinaldo { get; set; }
        public decimal ProporcionalVacaciones { get; set; }
        public decimal Proporcional20DiasPorAño { get; set; }
        public decimal AGUINALDO { get; set; }
        public decimal SUELDO { get; set; }
        public decimal VACACIONES { get; set; }
        public decimal PRIMA_VACACIONAL { get; set; }
        public decimal VACACIONES_PENDIENTE { get; set; }
        public decimal PRIMA_VACACIONES_PENDIENTE { get; set; }
        public decimal L_3MESES_SUELDO { get; set; }
        public decimal L_20DIAS_POR_AÑO { get; set; }
        public decimal PRIMA_ANTIGUEDAD { get; set; }
        public decimal ProporcionalPrimaAntiguedad { get; set; }
    }
}
