//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Cuotas_IMSS
    {
        public int IdCuota { get; set; }
        public int IdNomina { get; set; }
        public int IdFiniquito { get; set; }
        public decimal TotalPatron { get; set; }
        public decimal TotalObrero { get; set; }
        public decimal Cuota_Fija_Patron { get; set; }
        public decimal Excedente_Patron { get; set; }
        public decimal Excedente_Obrero { get; set; }
        public decimal PrestacionesDinero_Patron { get; set; }
        public decimal PrestacionesDinero_Obrero { get; set; }
        public decimal Pensionados_Patron { get; set; }
        public decimal Pensionados_Obrero { get; set; }
        public decimal InvalidezVida_Patron { get; set; }
        public decimal InvalidezVida_Obrero { get; set; }
        public decimal GuarderiasPrestaciones_Patron { get; set; }
        public decimal SeguroRetiro_Patron { get; set; }
        public decimal CesantiaVejez_Patron { get; set; }
        public decimal CesantiaVejez_Obrero { get; set; }
        public decimal Infonavit_Patron { get; set; }
        public decimal RiesgoTrabajo_Patron { get; set; }
    }
}
