//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Finiquito
    {
        public int IdFiniquito { get; set; }
        public int IdPeriodo { get; set; }
        public int IdContrato { get; set; }
        public int IdEmpleado { get; set; }
        public int IdCliente { get; set; }
        public int IdSucursal { get; set; }
        public decimal SalarioMinimo { get; set; }
        public decimal SueldoPrimaAntiguedad { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaBaja { get; set; }
        public System.DateTime FechaInicioAguinaldo { get; set; }
        public System.DateTime FechaInicioVacacion { get; set; }
        public int DiasLaborados { get; set; }
        public int DiasVacacionesParaCalculo { get; set; }
        public int DiasAguinaldoParaCalculo { get; set; }
        public int DiasDocePorA { get; set; }
        public int AguinaldoCorrespondiente { get; set; }
        public int VacacionesCorrespondiente { get; set; }
        public int PrimaVacacional { get; set; }
        public decimal SD { get; set; }
        public decimal SDI { get; set; }
        public decimal SBC { get; set; }
        public int DiasEjercicioFiscal { get; set; }
        public decimal L_3Meses_SueldoParaCalculo { get; set; }
        public decimal DiasSueldoPendiente { get; set; }
        public int VacacionesPendientes { get; set; }
        public int PrimaVacacionPendiente { get; set; }
        public decimal ProporcionalAguinaldo { get; set; }
        public decimal ProporcionalVacaciones { get; set; }
        public decimal ProporcionalPrimaAntiguedad { get; set; }
        public decimal Proporcional20DiasPorAño { get; set; }
        public decimal SUELDO { get; set; }
        public decimal VACACIONES { get; set; }
        public decimal PRIMA_VACACIONAL { get; set; }
        public decimal AGUINDALDO { get; set; }
        public decimal VACACIONES_PENDIENTE { get; set; }
        public decimal PRIMA_VACACIONES_PENDIENTE { get; set; }
        public decimal GRATIFICACION { get; set; }
        public decimal L_3MESES_SUELDO { get; set; }
        public decimal L_20DIAS_POR_AÑO { get; set; }
        public decimal PRIMA_ANTIGUEDAD { get; set; }
        public decimal COMPENSACION_X_INDEMNIZACION { get; set; }
        public decimal BaseGravableUltimoSueldo { get; set; }
        public decimal ISR_UltimoSueldo { get; set; }
        public decimal TasaParaLiquidacion { get; set; }
        public decimal Prima_Riesgo { get; set; }
        public decimal SubTotal_Finiquito { get; set; }
        public decimal ISR_Finiquito { get; set; }
        public decimal Total_Finiquito { get; set; }
        public decimal TOTAL_total { get; set; }
        public decimal ISR_Liquidacion { get; set; }
        public decimal SubTotal_Liquidacion { get; set; }
        public decimal Total_Liquidacion { get; set; }
        public decimal Subsidio_Finiquito { get; set; }
        public decimal Subsidio_Liquidacion { get; set; }
        public int L_AniosServicio { get; set; }
        public decimal L_UltimoSueldoMensualOrd { get; set; }
        public decimal L_IngresoAcumulable { get; set; }
        public decimal L_IngresoNoAcumulable { get; set; }
        public Nullable<int> IdEmpresaFiscal { get; set; }
        public Nullable<int> IdEmpresaComplemento { get; set; }
        public Nullable<int> IdEmpresaAsimilado { get; set; }
        public Nullable<int> IdEmpresaSindicato { get; set; }
        public int IdMetodo_Pago { get; set; }
        public decimal TotalPercepciones { get; set; }
        public decimal TotalDeducciones { get; set; }
        public decimal TotalComplemento { get; set; }
        public decimal TotalOtrosPagos { get; set; }
        public decimal SubsidioCausado { get; set; }
        public decimal SubsidioEntregado { get; set; }
        public string XMLSinTimbre { get; set; }
        public decimal UMA { get; set; }
        public bool EsLiquidacion { get; set; }
        public decimal DescuentosAplicados { get; set; }
        public bool CFDICreado { get; set; }
        public int TipoTarifa { get; set; }
        public int IdUsuario { get; set; }
        public decimal PensionAlimenticiaDelTotal { get; set; }
        public bool Art174 { get; set; }
    }
}
