//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_CFDI_Timbrado
    {
        public int IdTimbrado { get; set; }
        public string Version { get; set; }
        public string Serie { get; set; }
        public int Folio { get; set; }
        public int IdSucursal { get; set; }
        public int IdEjercicio { get; set; }
        public int IdPeriodo { get; set; }
        public int IdNomina { get; set; }
        public int IdFiniquito { get; set; }
        public int IdEmisor { get; set; }
        public int IdReceptor { get; set; }
        public bool ErrorTimbrado { get; set; }
        public bool Cancelado { get; set; }
        public bool IsPrueba { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<System.DateTime> FechaCertificacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string RFCEmisor { get; set; }
        public string RFCReceptor { get; set; }
        public string FolioFiscalUUID { get; set; }
        public decimal TotalRecibo { get; set; }
        public string XMLTimbrado { get; set; }
        public byte[] PDF { get; set; }
        public string CadenaOriginal { get; set; }
        public string XMLSinTimbre { get; set; }
        public string MensajeRespuesta { get; set; }
        public Nullable<int> UsuarioTimbro { get; set; }
        public Nullable<int> UsuarioCancelo { get; set; }
    }
}
