//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOM_Nomina_PrimaVacacional
    {
        public int Id { get; set; }
        public int IdPeriodo { get; set; }
        public int IdEmpleado { get; set; }
        public decimal DiasPrima { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal SD { get; set; }
        public decimal Isn { get; set; }
        public decimal Gravado { get; set; }
        public decimal Exento { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<int> IdUsuarioReg { get; set; }
    }
}
