//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int IdNotificacion { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioReg { get; set; }
        public int IdTipo { get; set; }
        public int IdCliente { get; set; }
        public int IdSucursal { get; set; }
        public string DatoReporte { get; set; }
        public int IdContrato { get; set; }
    }
}
