//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosConfig
    {
        public int IdConfig { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public int ValorInt { get; set; }
        public Nullable<bool> ValorBool { get; set; }
        public decimal ValorDecimal { get; set; }
        public string ValorString { get; set; }
    }
}
