//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int IdPermiso { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime Presentarse { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> Horas { get; set; }
        public Nullable<bool> ConGoce { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> PorHoras { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime FechaReg { get; set; }
    }
}
