//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int IdPrestamo { get; set; }
        public int IdEmpleadoContrato { get; set; }
        public int TipoPrestamo { get; set; }
        public decimal Monto { get; set; }
        public decimal MontoConInteres { get; set; }
        public decimal PorcentajeInteres { get; set; }
        public decimal Saldo { get; set; }
        public int Mensualidades { get; set; }
        public decimal DescuentoMensual { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Status { get; set; }
    }
}
