//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int IdSucursal { get; set; }
        public int IdCliente { get; set; }
        public string Ciudad { get; set; }
        public int IdEstado { get; set; }
        public int IdZonaSalario { get; set; }
        public bool Status { get; set; }
        public int TipoCalculoISN { get; set; }
        public bool CargaObreraPatronal { get; set; }
        public decimal PorcentajeServicio { get; set; }
        public decimal PorcentajeComision { get; set; }
        public System.DateTime FechaReg { get; set; }
    }
}
