//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYA_GlobalConfig
    {
        public int Id { get; set; }
        public string Server { get; set; }
        public string UsuarioServer { get; set; }
        public string PassServer { get; set; }
        public string UrlPac { get; set; }
        public string UsuarioPac { get; set; }
        public string PasswordPac { get; set; }
        public string UrlPacTest { get; set; }
        public string UsuarioPacTest { get; set; }
        public string PasswordPacTest { get; set; }
        public int Folios { get; set; }
        public string PathCertificados { get; set; }
    }
}
