//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public int Id { get; set; }
        public int IdPeridoVacaciones { get; set; }
        public int DiasTomados { get; set; }
        public bool Trabajado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime Presentarse { get; set; }
        public string Observaciones { get; set; }
        public bool Status { get; set; }
        public System.DateTime FechaReg { get; set; }
        public int Usuario { get; set; }
    }
}
