//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonaSalario
    {
        public int IdZonaSalario { get; set; }
        public string Zona { get; set; }
        public decimal SMG { get; set; }
        public decimal UMA { get; set; }
        public int LimiteMaxCotizacion { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public bool Status { get; set; }
    }
}
